/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.webtown.liferay.portlet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import hu.webtown.liferay.portlet.model.Episode;
import hu.webtown.liferay.portlet.service.EpisodeLocalServiceUtil;

/**
 * The extended model base implementation for the Episode service. Represents a row in the &quot;TvT_Episode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EpisodeImpl}.
 * </p>
 *
 * @author czeni
 * @see EpisodeImpl
 * @see hu.webtown.liferay.portlet.model.Episode
 * @generated
 */
public abstract class EpisodeBaseImpl extends EpisodeModelImpl
	implements Episode {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a episode model instance should use the {@link Episode} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			EpisodeLocalServiceUtil.addEpisode(this);
		}
		else {
			EpisodeLocalServiceUtil.updateEpisode(this);
		}
	}
}