/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.webtown.liferay.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import hu.webtown.liferay.portlet.model.TvShow;
import hu.webtown.liferay.portlet.model.TvShowModel;
import hu.webtown.liferay.portlet.model.TvShowSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TvShow service. Represents a row in the &quot;TvT_TvShow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link hu.webtown.liferay.portlet.model.TvShowModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TvShowImpl}.
 * </p>
 *
 * @author czeni
 * @see TvShowImpl
 * @see hu.webtown.liferay.portlet.model.TvShow
 * @see hu.webtown.liferay.portlet.model.TvShowModel
 * @generated
 */
@JSON(strict = true)
public class TvShowModelImpl extends BaseModelImpl<TvShow>
	implements TvShowModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tv show model instance should use the {@link hu.webtown.liferay.portlet.model.TvShow} interface instead.
	 */
	public static final String TABLE_NAME = "TvT_TvShow";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "tvShowId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "tvShowTitle", Types.VARCHAR },
			{ "tvShowPremierDate", Types.TIMESTAMP },
			{ "tvShowDescription", Types.VARCHAR },
			{ "tvShowImageUrl", Types.VARCHAR },
			{ "tvShowImageUuid", Types.VARCHAR },
			{ "tvShowImageTitle", Types.VARCHAR },
			{ "tvShowImageVersion", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table TvT_TvShow (uuid_ VARCHAR(75) null,tvShowId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,tvShowTitle VARCHAR(100) null,tvShowPremierDate DATE null,tvShowDescription VARCHAR(1000) null,tvShowImageUrl VARCHAR(1000) null,tvShowImageUuid VARCHAR(75) null,tvShowImageTitle VARCHAR(75) null,tvShowImageVersion VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TvT_TvShow";
	public static final String ORDER_BY_JPQL = " ORDER BY tvShow.tvShowTitle ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TvT_TvShow.tvShowTitle ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.hu.webtown.liferay.portlet.model.TvShow"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.hu.webtown.liferay.portlet.model.TvShow"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.hu.webtown.liferay.portlet.model.TvShow"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long TVSHOWID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long TVSHOWTITLE_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TvShow toModel(TvShowSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TvShow model = new TvShowImpl();

		model.setUuid(soapModel.getUuid());
		model.setTvShowId(soapModel.getTvShowId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTvShowTitle(soapModel.getTvShowTitle());
		model.setTvShowPremierDate(soapModel.getTvShowPremierDate());
		model.setTvShowDescription(soapModel.getTvShowDescription());
		model.setTvShowImageUrl(soapModel.getTvShowImageUrl());
		model.setTvShowImageUuid(soapModel.getTvShowImageUuid());
		model.setTvShowImageTitle(soapModel.getTvShowImageTitle());
		model.setTvShowImageVersion(soapModel.getTvShowImageVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TvShow> toModels(TvShowSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TvShow> models = new ArrayList<TvShow>(soapModels.length);

		for (TvShowSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.hu.webtown.liferay.portlet.model.TvShow"));

	public TvShowModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tvShowId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTvShowId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tvShowId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TvShow.class;
	}

	@Override
	public String getModelClassName() {
		return TvShow.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("tvShowId", getTvShowId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("tvShowTitle", getTvShowTitle());
		attributes.put("tvShowPremierDate", getTvShowPremierDate());
		attributes.put("tvShowDescription", getTvShowDescription());
		attributes.put("tvShowImageUrl", getTvShowImageUrl());
		attributes.put("tvShowImageUuid", getTvShowImageUuid());
		attributes.put("tvShowImageTitle", getTvShowImageTitle());
		attributes.put("tvShowImageVersion", getTvShowImageVersion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long tvShowId = (Long)attributes.get("tvShowId");

		if (tvShowId != null) {
			setTvShowId(tvShowId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String tvShowTitle = (String)attributes.get("tvShowTitle");

		if (tvShowTitle != null) {
			setTvShowTitle(tvShowTitle);
		}

		Date tvShowPremierDate = (Date)attributes.get("tvShowPremierDate");

		if (tvShowPremierDate != null) {
			setTvShowPremierDate(tvShowPremierDate);
		}

		String tvShowDescription = (String)attributes.get("tvShowDescription");

		if (tvShowDescription != null) {
			setTvShowDescription(tvShowDescription);
		}

		String tvShowImageUrl = (String)attributes.get("tvShowImageUrl");

		if (tvShowImageUrl != null) {
			setTvShowImageUrl(tvShowImageUrl);
		}

		String tvShowImageUuid = (String)attributes.get("tvShowImageUuid");

		if (tvShowImageUuid != null) {
			setTvShowImageUuid(tvShowImageUuid);
		}

		String tvShowImageTitle = (String)attributes.get("tvShowImageTitle");

		if (tvShowImageTitle != null) {
			setTvShowImageTitle(tvShowImageTitle);
		}

		String tvShowImageVersion = (String)attributes.get("tvShowImageVersion");

		if (tvShowImageVersion != null) {
			setTvShowImageVersion(tvShowImageVersion);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTvShowId() {
		return _tvShowId;
	}

	@Override
	public void setTvShowId(long tvShowId) {
		_columnBitmask |= TVSHOWID_COLUMN_BITMASK;

		if (!_setOriginalTvShowId) {
			_setOriginalTvShowId = true;

			_originalTvShowId = _tvShowId;
		}

		_tvShowId = tvShowId;
	}

	public long getOriginalTvShowId() {
		return _originalTvShowId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTvShowTitle() {
		if (_tvShowTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _tvShowTitle;
		}
	}

	@Override
	public void setTvShowTitle(String tvShowTitle) {
		_columnBitmask = -1L;

		_tvShowTitle = tvShowTitle;
	}

	@JSON
	@Override
	public Date getTvShowPremierDate() {
		return _tvShowPremierDate;
	}

	@Override
	public void setTvShowPremierDate(Date tvShowPremierDate) {
		_tvShowPremierDate = tvShowPremierDate;
	}

	@JSON
	@Override
	public String getTvShowDescription() {
		if (_tvShowDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _tvShowDescription;
		}
	}

	@Override
	public void setTvShowDescription(String tvShowDescription) {
		_tvShowDescription = tvShowDescription;
	}

	@JSON
	@Override
	public String getTvShowImageUrl() {
		if (_tvShowImageUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _tvShowImageUrl;
		}
	}

	@Override
	public void setTvShowImageUrl(String tvShowImageUrl) {
		_tvShowImageUrl = tvShowImageUrl;
	}

	@JSON
	@Override
	public String getTvShowImageUuid() {
		if (_tvShowImageUuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _tvShowImageUuid;
		}
	}

	@Override
	public void setTvShowImageUuid(String tvShowImageUuid) {
		_tvShowImageUuid = tvShowImageUuid;
	}

	@JSON
	@Override
	public String getTvShowImageTitle() {
		if (_tvShowImageTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _tvShowImageTitle;
		}
	}

	@Override
	public void setTvShowImageTitle(String tvShowImageTitle) {
		_tvShowImageTitle = tvShowImageTitle;
	}

	@JSON
	@Override
	public String getTvShowImageVersion() {
		if (_tvShowImageVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _tvShowImageVersion;
		}
	}

	@Override
	public void setTvShowImageVersion(String tvShowImageVersion) {
		_tvShowImageVersion = tvShowImageVersion;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				TvShow.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TvShow.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TvShow toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TvShow)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TvShowImpl tvShowImpl = new TvShowImpl();

		tvShowImpl.setUuid(getUuid());
		tvShowImpl.setTvShowId(getTvShowId());
		tvShowImpl.setGroupId(getGroupId());
		tvShowImpl.setCompanyId(getCompanyId());
		tvShowImpl.setUserId(getUserId());
		tvShowImpl.setUserName(getUserName());
		tvShowImpl.setCreateDate(getCreateDate());
		tvShowImpl.setModifiedDate(getModifiedDate());
		tvShowImpl.setTvShowTitle(getTvShowTitle());
		tvShowImpl.setTvShowPremierDate(getTvShowPremierDate());
		tvShowImpl.setTvShowDescription(getTvShowDescription());
		tvShowImpl.setTvShowImageUrl(getTvShowImageUrl());
		tvShowImpl.setTvShowImageUuid(getTvShowImageUuid());
		tvShowImpl.setTvShowImageTitle(getTvShowImageTitle());
		tvShowImpl.setTvShowImageVersion(getTvShowImageVersion());

		tvShowImpl.resetOriginalValues();

		return tvShowImpl;
	}

	@Override
	public int compareTo(TvShow tvShow) {
		int value = 0;

		value = getTvShowTitle().compareTo(tvShow.getTvShowTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TvShow)) {
			return false;
		}

		TvShow tvShow = (TvShow)obj;

		long primaryKey = tvShow.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TvShowModelImpl tvShowModelImpl = this;

		tvShowModelImpl._originalUuid = tvShowModelImpl._uuid;

		tvShowModelImpl._originalTvShowId = tvShowModelImpl._tvShowId;

		tvShowModelImpl._setOriginalTvShowId = false;

		tvShowModelImpl._originalGroupId = tvShowModelImpl._groupId;

		tvShowModelImpl._setOriginalGroupId = false;

		tvShowModelImpl._originalCompanyId = tvShowModelImpl._companyId;

		tvShowModelImpl._setOriginalCompanyId = false;

		tvShowModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TvShow> toCacheModel() {
		TvShowCacheModel tvShowCacheModel = new TvShowCacheModel();

		tvShowCacheModel.uuid = getUuid();

		String uuid = tvShowCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tvShowCacheModel.uuid = null;
		}

		tvShowCacheModel.tvShowId = getTvShowId();

		tvShowCacheModel.groupId = getGroupId();

		tvShowCacheModel.companyId = getCompanyId();

		tvShowCacheModel.userId = getUserId();

		tvShowCacheModel.userName = getUserName();

		String userName = tvShowCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tvShowCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tvShowCacheModel.createDate = createDate.getTime();
		}
		else {
			tvShowCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tvShowCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tvShowCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tvShowCacheModel.tvShowTitle = getTvShowTitle();

		String tvShowTitle = tvShowCacheModel.tvShowTitle;

		if ((tvShowTitle != null) && (tvShowTitle.length() == 0)) {
			tvShowCacheModel.tvShowTitle = null;
		}

		Date tvShowPremierDate = getTvShowPremierDate();

		if (tvShowPremierDate != null) {
			tvShowCacheModel.tvShowPremierDate = tvShowPremierDate.getTime();
		}
		else {
			tvShowCacheModel.tvShowPremierDate = Long.MIN_VALUE;
		}

		tvShowCacheModel.tvShowDescription = getTvShowDescription();

		String tvShowDescription = tvShowCacheModel.tvShowDescription;

		if ((tvShowDescription != null) && (tvShowDescription.length() == 0)) {
			tvShowCacheModel.tvShowDescription = null;
		}

		tvShowCacheModel.tvShowImageUrl = getTvShowImageUrl();

		String tvShowImageUrl = tvShowCacheModel.tvShowImageUrl;

		if ((tvShowImageUrl != null) && (tvShowImageUrl.length() == 0)) {
			tvShowCacheModel.tvShowImageUrl = null;
		}

		tvShowCacheModel.tvShowImageUuid = getTvShowImageUuid();

		String tvShowImageUuid = tvShowCacheModel.tvShowImageUuid;

		if ((tvShowImageUuid != null) && (tvShowImageUuid.length() == 0)) {
			tvShowCacheModel.tvShowImageUuid = null;
		}

		tvShowCacheModel.tvShowImageTitle = getTvShowImageTitle();

		String tvShowImageTitle = tvShowCacheModel.tvShowImageTitle;

		if ((tvShowImageTitle != null) && (tvShowImageTitle.length() == 0)) {
			tvShowCacheModel.tvShowImageTitle = null;
		}

		tvShowCacheModel.tvShowImageVersion = getTvShowImageVersion();

		String tvShowImageVersion = tvShowCacheModel.tvShowImageVersion;

		if ((tvShowImageVersion != null) && (tvShowImageVersion.length() == 0)) {
			tvShowCacheModel.tvShowImageVersion = null;
		}

		return tvShowCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", tvShowId=");
		sb.append(getTvShowId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", tvShowTitle=");
		sb.append(getTvShowTitle());
		sb.append(", tvShowPremierDate=");
		sb.append(getTvShowPremierDate());
		sb.append(", tvShowDescription=");
		sb.append(getTvShowDescription());
		sb.append(", tvShowImageUrl=");
		sb.append(getTvShowImageUrl());
		sb.append(", tvShowImageUuid=");
		sb.append(getTvShowImageUuid());
		sb.append(", tvShowImageTitle=");
		sb.append(getTvShowImageTitle());
		sb.append(", tvShowImageVersion=");
		sb.append(getTvShowImageVersion());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("hu.webtown.liferay.portlet.model.TvShow");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowId</column-name><column-value><![CDATA[");
		sb.append(getTvShowId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowTitle</column-name><column-value><![CDATA[");
		sb.append(getTvShowTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowPremierDate</column-name><column-value><![CDATA[");
		sb.append(getTvShowPremierDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowDescription</column-name><column-value><![CDATA[");
		sb.append(getTvShowDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowImageUrl</column-name><column-value><![CDATA[");
		sb.append(getTvShowImageUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowImageUuid</column-name><column-value><![CDATA[");
		sb.append(getTvShowImageUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowImageTitle</column-name><column-value><![CDATA[");
		sb.append(getTvShowImageTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tvShowImageVersion</column-name><column-value><![CDATA[");
		sb.append(getTvShowImageVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TvShow.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { TvShow.class };
	private String _uuid;
	private String _originalUuid;
	private long _tvShowId;
	private long _originalTvShowId;
	private boolean _setOriginalTvShowId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _tvShowTitle;
	private Date _tvShowPremierDate;
	private String _tvShowDescription;
	private String _tvShowImageUrl;
	private String _tvShowImageUuid;
	private String _tvShowImageTitle;
	private String _tvShowImageVersion;
	private long _columnBitmask;
	private TvShow _escapedModel;
}